# -*- coding: utf-8 -*-
"""V1.0 场景池：REAL_WORLD 12个 + SPACE_LIFE 7个。
每个场景只保存 space / actions / effects / lighting 四类信息。
"""

from .models import ScenePackage

REAL_SCENES = {
    "BEDROOM": ScenePackage(
        id="BEDROOM", name="卧室", domain="REAL_WORLD",
        space="普通卧室，床边、木地板、窗帘和床头小物",
        actions={
            "STILL": ["她安静站在床边，看向镜头", "她坐在床边，双手自然放在膝盖上，看向镜头"],
            "RELAXED": ["她坐在床边，一条腿收起来，肩膀自然塌下，看向窗外",
                        "她靠着床头，膝盖微收，手里搭着一件叠好的衣服"],
            "OBSERVING": ["她站在窗边，看着窗外，手搭在窗台上", "她坐在床边，低头看着手里的东西"],
            "INTERACTING": ["她拿起床头的杯子，低头看了一眼", "她正在叠一件衣服，动作停在中间"],
            "MOVING": ["她正从床边起身，身体前倾，手撑着床沿", "她转身走向门口，头刚回过来"],
            "REACTING": ["下午的光突然照进房间，她微微眯了一下眼睛",
                         "窗外传来声音，她抬头看向窗边，手停在半空"],
            "JOY": ["她被什么逗到，刚忍不住笑出来，嘴角先起来", "她坐在床边笑出来，眼睛弯着"],
        },
        effects=["下午窗光落在她半张脸上", "窗帘被风轻轻带起"],
        lighting=["柔和下午窗光", "清晨窗光", "台灯暖光"],
        preferred_lenses=[50, 70, 85], preferred_frames=["close_up", "half_body"]),
    "HOME_WINDOW": ScenePackage(
        id="HOME_WINDOW", name="家里窗边", domain="REAL_WORLD",
        space="家里窗边，窗框、窗帘和窗台",
        actions={
            "STILL": ["她站在窗边，安静看向镜头", "她靠在窗框旁，双手垂在身侧"],
            "RELAXED": ["她靠在窗边，肩膀放松，看向窗外", "她侧身靠着窗台，手搭在窗沿"],
            "OBSERVING": ["她看着窗外街道，眼神安静", "她望向窗外的树和光"],
            "INTERACTING": ["她正在拉窗帘，手停在帘布上", "她伸手整理窗台上的一本书"],
            "MOVING": ["她正从窗边走开，头刚回来看镜头", "她走向窗边，脚步刚停"],
            "REACTING": ["风把窗帘吹起，她抬手按住窗帘一角", "窗光晃了一下，她微微侧头"],
            "JOY": ["她看着窗外笑了一下，没有完全笑开", "她转回来看镜头，嘴角还带着一点笑"],
        },
        effects=["窗光从侧面照在她脸上", "窗帘被风轻轻吹起"],
        lighting=["下午窗光", "清晨窗光"],
        preferred_lenses=[50, 70], preferred_frames=["close_up", "half_body"]),
    "CAFE": ScenePackage(
        id="CAFE", name="咖啡馆", domain="REAL_WORLD",
        space="咖啡馆靠窗座位，木桌、咖啡杯、书架和暖色墙面",
        actions={
            "STILL": ["她坐在靠窗座位，安静看向镜头", "她坐在桌边，双手放在桌上，看向镜头"],
            "RELAXED": ["她坐在窗边，肩膀松下来，视线落在杯沿", "她靠着椅背，手里握着杯子，没有看镜头"],
            "OBSERVING": ["她看着窗外来往的人，眼神安静", "她低头看着桌上的咖啡杯"],
            "INTERACTING": ["她双手捧着咖啡杯，刚喝了一口", "她正在和对面的人说话，手停在桌边"],
            "MOVING": ["她正起身离开座位，身体还侧着", "她端着一杯咖啡走向窗边，头刚转过来"],
            "REACTING": ["热咖啡的蒸汽扑到脸上，她微微眯了一下眼",
                         "窗外突然一阵风，她转头看了一眼"],
            "JOY": ["她听对面的人说话，刚忍不住笑出来", "她低头笑了一下，肩膀轻轻动"],
        },
        effects=["窗边自然光从侧面落在她脸上", "热咖啡的蒸汽轻轻飘起"],
        lighting=["窗边自然光", "暖色室内光"],
        preferred_lenses=[50, 70, 85], preferred_frames=["close_up", "half_body"]),
    "CITY_STREET": ScenePackage(
        id="CITY_STREET", name="城市街道", domain="REAL_WORLD",
        space="普通城市街道，人行道、路灯、店铺门面和远处车辆",
        actions={
            "STILL": ["她站在人行道上，安静看向镜头", "她站在街边，双手自然垂落，看向镜头"],
            "RELAXED": ["她靠在路灯杆旁，肩膀放松，看向街道", "她站在街边，双手插在口袋里"],
            "OBSERVING": ["她看着街道远处，眼神安静", "她站在路口，看着来往的车"],
            "INTERACTING": ["她正在看手机，抬头看向镜头", "她接过一杯外带饮料，低头看了一眼"],
            "MOVING": ["她正沿人行道往前走，身体还在移动", "她走到路口，头刚转回来"],
            "REACTING": ["一阵风把头发吹到脸上，她抬手拨开", "远处车灯闪了一下，她微微眯眼"],
            "JOY": ["她看到什么好笑的事，刚笑出来", "她转回来看镜头，嘴角带着没收住的笑"],
        },
        effects=["一阵风把头发吹到脸侧", "午后阳光从楼间照下来"],
        lighting=["白天自然光", "午后阳光", "黄昏城市光"],
        preferred_lenses=[35, 50], preferred_frames=["half_body", "full_body", "three_quarter"]),
    "BUS_STOP": ScenePackage(
        id="BUS_STOP", name="公交站", domain="REAL_WORLD",
        space="公交站亭、站牌、道路、护栏、树木和远处车辆",
        actions={
            "STILL": ["她站在站牌旁，安静看向镜头", "她站在公交站，双手自然垂落"],
            "RELAXED": ["她靠着站亭，肩膀缩着，看向道路", "她站在护栏边，双手插进口袋"],
            "OBSERVING": ["她看着来车的方向，眼神安静", "她低头看着站牌上的路线"],
            "INTERACTING": ["她正在整理围巾，手停在领口", "她低头看了看手里的东西"],
            "MOVING": ["她正走向站台边缘，头刚回过来", "她看到车来了，从站牌旁走出来，身体还在动"],
            "REACTING": ["冷风把碎发吹到脸上，她抬手抓住围巾",
                         "冬日下午的光照在站牌玻璃上，她微微眯眼"],
            "JOY": ["她看到熟人，刚笑出来", "她低头笑了一下，围巾被风带起一角"],
        },
        effects=["冷风把碎发吹到脸前", "冬日下午的光照在站牌玻璃上"],
        lighting=["阴天冷光", "冬日下午光", "黄昏城市柔光"],
        preferred_lenses=[35, 50, 85], preferred_frames=["half_body", "three_quarter"]),
    "PARK": ScenePackage(
        id="PARK", name="公园", domain="REAL_WORLD",
        space="公园草地与树木，长椅、步道和落叶",
        actions={
            "STILL": ["她站在草地上，安静看向镜头", "她站在步道上，双手自然垂落"],
            "RELAXED": ["她坐在长椅上，肩膀松下来，看向远处", "她坐在草地上，膝盖收向一侧，手撑在地面"],
            "OBSERVING": ["她看着树下的光斑，眼神安静", "她站在树下，看着远处的步道"],
            "INTERACTING": ["她正在给长椅上的包拉上拉链", "她弯腰捡起一片落叶，看了一眼"],
            "MOVING": ["她正沿步道往前走，身体还在移动", "她从树荫里走出来，头刚转过来"],
            "REACTING": ["风把落叶吹到她脚边，她低头看了一眼",
                         "阳光穿过树叶晃了一下，她微微眯眼"],
            "JOY": ["她走在步道上，刚忍不住笑出来", "她坐在长椅上笑了一下，眼睛弯着"],
        },
        effects=["风把落叶吹到她脚边", "阳光穿过树叶在她脸上留下光斑"],
        lighting=["白天自然光", "午后光", "黄昏柔光"],
        preferred_lenses=[35, 50, 70], preferred_frames=["half_body", "full_body"]),
    "RIVERSIDE": ScenePackage(
        id="RIVERSIDE", name="河边", domain="REAL_WORLD",
        space="河边堤岸，栏杆、水面和对岸城市",
        actions={
            "STILL": ["她站在河边栏杆旁，安静看向镜头", "她站在堤岸上，双手放在栏杆上"],
            "RELAXED": ["她靠在栏杆上，肩膀放松，看着水面", "她侧身靠着栏杆，手搭在栏面"],
            "OBSERVING": ["她看着河面，眼神安静", "她望向对岸的城市，风把头发吹起一点"],
            "INTERACTING": ["她正在用手机拍河面，抬头看向镜头", "她整理了一下外套领口"],
            "MOVING": ["她正沿堤岸往前走，头刚转回来", "她从栏杆边转身，身体还在动"],
            "REACTING": ["河风把头发吹到脸上，她抬手按住发梢",
                         "傍晚水面反光晃到她脸上，她微微侧头"],
            "JOY": ["她看着水面笑了一下，没有完全笑开", "她转回来看镜头，嘴角带着一点笑"],
        },
        effects=["河风把头发吹向一侧", "傍晚水面反光照在她脸上"],
        lighting=["白天自然光", "黄昏暖光", "傍晚水面反光"],
        preferred_lenses=[35, 50, 85], preferred_frames=["half_body", "three_quarter"]),
    "SEASIDE": ScenePackage(
        id="SEASIDE", name="海边", domain="REAL_WORLD",
        space="海边堤岸和沙滩，海面、天空和远处船只",
        actions={
            "STILL": ["她站在海边，安静看向镜头", "她站在沙滩上，双手自然垂落"],
            "RELAXED": ["她坐在沙滩上，膝盖收向一侧，看向海面", "她靠在堤岸栏杆上，肩膀放松"],
            "OBSERVING": ["她看着海平面，眼神安静", "她望向远处的船，风把头发吹起"],
            "INTERACTING": ["她正在系外套扣子，手停在胸前", "她弯腰捡起一个贝壳，看了一眼"],
            "MOVING": ["她正沿着沙滩走，身体还在移动", "她从浪边走过来，头刚转回来看镜头"],
            "REACTING": ["海风把头发吹到脸上，她抬手按住", "傍晚的海面反光照在她脸上，她微微眯眼"],
            "JOY": ["她被海浪声逗到，刚笑出来", "她站在海边笑了一下，眼睛弯着"],
        },
        effects=["海风把头发吹到脸侧", "傍晚海面反光照在她脸上"],
        lighting=["白天明亮自然光", "黄昏暖光"],
        preferred_lenses=[35, 50, 70], preferred_frames=["half_body", "full_body"]),
    "FOREST": ScenePackage(
        id="FOREST", name="森林", domain="REAL_WORLD",
        space="树林，树干、枝叶和地面光斑",
        actions={
            "STILL": ["她站在树干旁，安静看向镜头", "她站在林间空地上，双手自然垂落"],
            "RELAXED": ["她靠着树干，肩膀放松，看向林间", "她坐在树根旁，膝盖收向一侧"],
            "OBSERVING": ["她看着树冠间漏下的光，眼神安静", "她低头看着地面上的光斑"],
            "INTERACTING": ["她伸手碰了一下树枝上的叶子", "她正在整理背包带，手停在肩带"],
            "MOVING": ["她正沿林间小路往前走，头刚转回来", "她从树影里走出来，身体还在动"],
            "REACTING": ["风穿过树林，头发被吹到脸上，她抬手拨开",
                         "一束光突然照在她脸上，她微微侧头"],
            "JOY": ["她走在林间，刚忍不住笑出来", "她靠在树边笑了一下"],
        },
        effects=["风穿过树林，头发被吹到脸侧", "一束光从树冠间照在她脸上"],
        lighting=["林间散射光", "树冠漏下的光"],
        preferred_lenses=[35, 50], preferred_frames=["half_body", "full_body"]),
    "GRASSLAND": ScenePackage(
        id="GRASSLAND", name="草地", domain="REAL_WORLD",
        space="开阔草地，远处山丘连着树线，天空",
        actions={
            "STILL": ["她站在草地上，安静看向镜头", "她站在草坡上，双手自然垂落"],
            "RELAXED": ["她坐在草地上，膝盖收向一侧，手撑在地面", "她躺在草坡上，手垫在脑后，看向天空"],
            "OBSERVING": ["她看着远处的山丘，眼神安静", "她望着天空，风把头发吹起一点"],
            "INTERACTING": ["她正在整理外套袖子，手停在手腕", "她弯腰碰了一下草尖"],
            "MOVING": ["她正沿草坡往前走，身体还在移动", "她从坡上走下来，头刚转回来"],
            "REACTING": ["草原上的风把头发吹乱，她抬手按住发梢",
                         "傍晚低光从侧面照来，她微微眯眼"],
            "JOY": ["她站在草地上，刚笑出来", "她坐在草坡上笑了一下，眼睛弯着"],
        },
        effects=["草原的风把头发吹乱", "傍晚低角度光从侧面照来"],
        lighting=["白天自然光", "黄昏低角度光"],
        preferred_lenses=[35, 50, 70], preferred_frames=["half_body", "full_body"]),
    "OLD_TOWN": ScenePackage(
        id="OLD_TOWN", name="老城街巷", domain="REAL_WORLD",
        space="老城街巷，砖墙、石板路、旧门窗和晾晒的衣物",
        actions={
            "STILL": ["她站在老城巷子里，安静看向镜头", "她站在石板路上，双手自然垂落"],
            "RELAXED": ["她靠在旧墙边，肩膀放松，看向巷子", "她坐在石阶上，手搭在膝盖"],
            "OBSERVING": ["她看着巷子深处，眼神安静", "她抬头看着旧窗户，风把头发吹起"],
            "INTERACTING": ["她正在看墙边的一扇旧门，手停在门框", "她整理了一下衣角"],
            "MOVING": ["她正沿石板路往前走，头刚转回来", "她从巷口走进来，身体还在动"],
            "REACTING": ["巷子里的风把头发吹到脸上，她抬手拨开",
                         "午后的光从屋檐间照下来，她微微眯眼"],
            "JOY": ["她走在老城里，刚忍不住笑出来", "她站在墙边笑了一下"],
        },
        effects=["巷子里的风把头发吹到脸前", "午后的光从屋檐间照下"],
        lighting=["午后天光", "黄昏暖光", "阴天漫射光"],
        preferred_lenses=[35, 50], preferred_frames=["half_body", "three_quarter"]),
    "TRAVEL_ROOM": ScenePackage(
        id="TRAVEL_ROOM", name="旅行住处", domain="REAL_WORLD",
        space="旅行住处，简单床铺、行李箱、小桌和窗户",
        actions={
            "STILL": ["她站在窗前，安静看向镜头", "她坐在床边，双手放在膝盖上"],
            "RELAXED": ["她坐在床沿，肩膀松下来，看向窗外", "她靠着床头，手里拿着地图"],
            "OBSERVING": ["她看着窗外陌生的街道，眼神安静", "她低头看着手里的车票"],
            "INTERACTING": ["她正在打开行李箱，动作停在中间", "她拿起桌上的水杯，喝了一口"],
            "MOVING": ["她正从床边起身，身体前倾", "她走向门口，头刚回过来"],
            "REACTING": ["窗外透进来的光晃了一下，她微微侧头", "楼下的声音传来，她抬头看向窗外"],
            "JOY": ["她看到窗外的风景，刚笑出来", "她坐在床边笑了一下"],
        },
        effects=["窗外透进的光落在她身上", "窗帘被风轻轻带起"],
        lighting=["下午窗光", "台灯暖光"],
        preferred_lenses=[50, 70], preferred_frames=["close_up", "half_body"]),
}

SPACE_SCENES = {
    "ORBITAL_BEDROOM": ScenePackage(
        id="ORBITAL_BEDROOM", name="太空卧室", domain="SPACE_LIFE",
        space="类似飞机休息舱的小卧室，布料床铺、储物袋、小台灯、磨损塑料墙面和小舷窗，窗外地球",
        actions={
            "STILL": ["她坐在床边，安静看向镜头", "她站在小舱室中央，双手自然垂落"],
            "RELAXED": ["她靠在床头，膝盖微收，手里搭着一件叠好的衣物",
                        "她坐在床边，肩膀松下来，看向窗外地球"],
            "OBSERVING": ["她看着舷窗外的地球，眼神安静", "她低头看着手里的小物件"],
            "INTERACTING": ["她正在整理储物袋，手停在袋口", "她拿起台灯旁的杯子，低头看了一眼"],
            "MOVING": ["她正从床边起身，身体前倾，手撑着床沿", "她转身走向舱门，头刚回过来"],
            "REACTING": ["舱灯突然亮起，她微微眯了一下眼睛", "窗外地球的光晃了一下，她抬头看向舷窗"],
            "JOY": ["她看着窗外的地球，刚笑出来", "她坐在床边笑了一下"],
        },
        effects=["台灯的光落在她半张脸上", "舷窗外地球的光照在她脸上"],
        lighting=["柔和台灯光", "地球反射光与台灯混合"],
        preferred_lenses=[50, 70], preferred_frames=["close_up", "half_body"]),
    "LIVING_CABIN": ScenePackage(
        id="LIVING_CABIN", name="生活舱", domain="SPACE_LIFE",
        space="两层高生活舱，粗大结构梁，连续三道舱门向远处缩小，几十米纵深，工作灯，窗外地球",
        actions={
            "STILL": ["她站在生活舱中央，安静看向镜头", "她站在结构梁旁，双手自然垂落"],
            "RELAXED": ["她靠在舱壁旁，肩膀放松，看向窗外", "她坐在舱内的椅子上，手搭在扶手上"],
            "OBSERVING": ["她看着远处的舱门，眼神安静", "她望向窗外地球"],
            "INTERACTING": ["她正在和同事说话，手停在半空", "她低头看着手里的平板，抬头看向镜头"],
            "MOVING": ["她正沿舱内通道往前走，头刚转回来", "她穿过一道舱门，身体还在动"],
            "REACTING": ["工作灯闪了一下，她微微抬头", "窗外地球的光照进来，她眯了一下眼"],
            "JOY": ["她走在舱内，刚忍不住笑出来", "她站在窗边笑了一下"],
        },
        effects=["工作灯从上方照下", "窗外地球的光从侧面照来"],
        lighting=["工作灯", "地球反射光与工作灯混合"],
        preferred_lenses=[35, 50], preferred_frames=["half_body", "full_body"]),
    "OBSERVATION_WINDOW": ScenePackage(
        id="OBSERVATION_WINDOW", name="舷窗", domain="SPACE_LIFE",
        space="金属窗框的大舷窗，窗外地球与星空，窗边有扶手",
        actions={
            "STILL": ["她站在舷窗前，安静看向镜头", "她站在窗边，双手放在扶手上"],
            "RELAXED": ["她靠在窗框旁，肩膀放松，看着窗外", "她侧身靠着窗沿，手搭在窗台"],
            "OBSERVING": ["她看着窗外的地球，眼神安静", "她望着窗外，眼神安静"],
            "INTERACTING": ["她正在调整窗边的小灯，手停在开关", "她擦了擦窗沿的灰尘，抬头看镜头"],
            "MOVING": ["她正从窗边走开，头刚回来看镜头", "她走向舷窗，脚步刚停"],
            "REACTING": ["地球的光从窗外照进来，她微微眯眼", "窗外轨道光线变化，她抬头看"],
            "JOY": ["她看着窗外，刚笑出来", "她转回来看镜头，嘴角还带着一点笑"],
        },
        effects=["地球的光从窗外照在她脸上", "窗框投下细长的影子"],
        lighting=["窗外地球反射光", "冷白舱灯"],
        preferred_lenses=[50, 70, 85], preferred_frames=["close_up", "half_body"]),
    "LONG_MODULE": ScenePackage(
        id="LONG_MODULE", name="长通道", domain="SPACE_LIFE",
        space="长通道模块，管线、舱壁固定件、连续舱门，远处透入自然光",
        actions={
            "STILL": ["她站在通道里，安静看向镜头", "她站在舱门旁，双手自然垂落"],
            "RELAXED": ["她靠着舱壁，肩膀放松，看向通道深处", "她站在管线旁，手搭在固定件上"],
            "OBSERVING": ["她看着通道深处的光，眼神安静", "她低头看着地面上的管线走向"],
            "INTERACTING": ["她正在检查舱壁上的固定扣，手停在上面", "她低头看着手里的工具"],
            "MOVING": ["她正沿通道往前走，头刚转回来", "她穿过一道舱门，身体还在动"],
            "REACTING": ["远处的光突然变化，她抬头看了一眼", "她撞到一根软管，身体停了一下，回头"],
            "JOY": ["她走在通道里，刚笑出来", "她站在舱门边笑了一下"],
        },
        effects=["远处的自然光透进通道", "工作灯从上方照下"],
        lighting=["远处自然光与工作灯", "冷白舱灯"],
        preferred_lenses=[35, 50], preferred_frames=["half_body", "full_body"]),
    "MAINTENANCE_AREA": ScenePackage(
        id="MAINTENANCE_AREA", name="维修区", domain="SPACE_LIFE",
        space="维修区，管线、大型机械结构、金属踏板、工具架和工作灯",
        actions={
            "STILL": ["她站在维修区，安静看向镜头", "她站在金属踏板旁，双手自然垂落"],
            "RELAXED": ["她靠在工具架旁，肩膀放松，擦了一下额头", "她坐在踏板上，手搭在膝盖"],
            "OBSERVING": ["她看着面前的机械结构，眼神安静", "她低头检查手里的零件"],
            "INTERACTING": ["她正在拧一颗螺栓，动作停在中间", "她把手套摘下一只，抬头看向镜头"],
            "MOVING": ["她正从机械旁走过，头刚转回来", "她弯腰拿起工具，身体还在动"],
            "REACTING": ["工作灯晃了一下，她抬头眯眼", "金属表面反光晃到她脸上，她微微侧头"],
            "JOY": ["她修好一处设备，刚笑出来", "她站在维修区笑了一下"],
        },
        effects=["工作灯从上方照下，金属表面有反光", "维修灯照亮她脸侧"],
        lighting=["维修工作灯", "冷白舱灯与工作灯混合"],
        preferred_lenses=[35, 50], preferred_frames=["half_body", "three_quarter"]),
    "EQUIPMENT_PREP": ScenePackage(
        id="EQUIPMENT_PREP", name="装备准备区", domain="SPACE_LIFE",
        space="装备准备区，厚重宇航服、织带、金属扣件和工作灯",
        actions={
            "STILL": ["她站在装备区，安静看向镜头", "她站在宇航服旁，双手自然垂落"],
            "RELAXED": ["她靠在装备架旁，肩膀放松，整理了一下内层服领口",
                        "她坐在凳子上，手搭在膝盖"],
            "OBSERVING": ["她看着面前厚重宇航服，眼神安静", "她低头检查织带扣件"],
            "INTERACTING": ["她正在穿内层服，动作停在整理领口", "她正在扣织带，手停在扣件上"],
            "MOVING": ["她正走向宇航服，头刚回过来", "她从装备架旁转身，身体还在动"],
            "REACTING": ["工作灯亮起，她微微眯眼", "她拉了一下织带，身体顿了一下"],
            "JOY": ["她看着装备，刚笑出来", "她站在装备区笑了一下"],
        },
        effects=["工作灯照亮装备区", "金属扣件上有反光"],
        lighting=["工作灯", "冷白舱灯"],
        preferred_lenses=[50, 70], preferred_frames=["half_body", "three_quarter"]),
    "OBSERVATION_DECK": ScenePackage(
        id="OBSERVATION_DECK", name="观察甲板", domain="SPACE_LIFE",
        space="观察甲板，前景栏杆、大玻璃、外部结构和远处地球",
        actions={
            "STILL": ["她站在观察甲板上，安静看向镜头", "她站在栏杆前，双手放在栏杆上"],
            "RELAXED": ["她靠在栏杆上，肩膀放松，看向窗外地球", "她侧身靠着栏杆，手搭在栏面"],
            "OBSERVING": ["她看着远处的地球，眼神安静", "她望向外部结构之间的星空"],
            "INTERACTING": ["她正在调整相机，抬头看向镜头", "她整理了一下外套领口"],
            "MOVING": ["她正沿甲板往前走，头刚转回来", "她从栏杆边转身，身体还在动"],
            "REACTING": ["地球的光从玻璃外照进来，她微微眯眼", "外部结构的影子扫过，她抬头看"],
            "JOY": ["她看着窗外的地球，刚笑出来", "她转回来看镜头，嘴角带着一点笑"],
        },
        effects=["地球的光从玻璃外照进来", "外部结构的影子投在甲板上"],
        lighting=["窗外地球反射光", "冷白舱灯与地球光混合"],
        preferred_lenses=[35, 50, 70], preferred_frames=["half_body", "environmental_portrait"]),
}


def get_scene(scene_id: str) -> ScenePackage:
    if scene_id in REAL_SCENES:
        return REAL_SCENES[scene_id]
    if scene_id in SPACE_SCENES:
        return SPACE_SCENES[scene_id]
    raise KeyError("未知场景：%s" % scene_id)
